const express = require('express');
const router = express.Router();


var TeleSignSDK = require('telesignsdk');

const customerId = "3CF93A12-34E6-4216-9621-A0F780586654";
const apiKey = "BSQBwJXAfB8o/VSryIqG1prk3d5pyFxgEl2lRIDoAnJntXxyNqVYJDcl+IQNPNUYpvpf/IYBPSQfYUeT2X/THA==";
const rest_endpoint = "https://rest-api.telesign.com";
const timeout = 10*1000; // 10 secs

const client = new TeleSignSDK( customerId,
    apiKey,
    rest_endpoint,
    timeout // optional
    // userAgent
);

const phoneNumber = "916262600022";
const message = "You're scheduled for a dentist appointment at 2:30PM.";
const messageType = "MKT";

console.log("## MessagingClient.message ##");

function messageCallback(error, responseBody) {

    if (error === null) {
      function generateOTP() {

          // Declare a digits variable
          // which stores all digits
          var digits = '0123456789';
          let OTP = '';
          for (let i = 0; i < 4; i++ ) {
              OTP += digits[Math.floor(Math.random() * 10)];
          }
          return OTP;
      }
      var code = generateOTP();
      console.log(code);
        console.log(`Messaging response for messaging phone number: ${phoneNumber}` +
            ` => code:` + code +
            `, description: ${responseBody['status']['description']}`);
    } else {
        console.error("Unable to send message. " + error);
    }
}

client.sms.message(messageCallback, phoneNumber, message, messageType);



var options = {
  phoneNumber: '8181008484', // required

  verifyCode: 'code', // optional, defaults to random value generated by TeleSign
  template: 'Your code is $$CODE$$' // optional, must include a $$CODE$$ placeholder to integrate the verifyCode token
};




module.exports = router;
